### ISSUE TITLE
Panic on Trap in Latest Release

### ISSUE THREAD

**Issue by naftulikay** [tailhook/signal#11]
I receive a panic when trying to use the latest `signal` with the latest stable Rust:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(EINVAL)', src/libcore/result.rs:999:5
stack backtrace:
   0:     0x55fd357447b3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h6485381528590a55
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x55fd3574031b - std::sys_common::backtrace::_print::h49a82ae9552e35c7
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x55fd357435d6 - std::panicking::default_hook::{{closure}}::he20974adbefcc046
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x55fd35743369 - std::panicking::default_hook::he4af6af4ac7fef7b
                               at src/libstd/panicking.rs:211
   4:     0x55fd35743c7f - std::panicking::rust_panic_with_hook::h057ff03eb4c8000f
                               at src/libstd/panicking.rs:474
   5:     0x55fd35743801 - std::panicking::continue_panic_fmt::ha6d6ae144369025b
                               at src/libstd/panicking.rs:381
   6:     0x55fd357436e5 - rust_begin_unwind
                               at src/libstd/panicking.rs:308
   7:     0x55fd35755ddc - core::panicking::panic_fmt::hc4f83bfed80aeabd
                               at src/libcore/panicking.rs:85
   8:     0x55fd354672e0 - core::result::unwrap_failed::h5193288808725576
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9:     0x55fd35465e60 - core::result::Result<T,E>::unwrap::h34639d06772452f1
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10:     0x55fd354656cb - signal::trap::Trap::trap::h5ef0f45612dc0baf
                               at /home/naftuli/.cargo/registry/src/github.com-1ecc6299db9ec823/signal-0.6.0/src/trap.rs:53
  11:     0x55fd35462b05 - emissary::main::h62067733c7ea1341
                               at src/main.rs:15
  12:     0x55fd35462a4f - std::rt::lang_start::{{closure}}::h499a5033e8991994
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  13:     0x55fd35743682 - std::panicking::try::do_call::hc3d8373a0b215f51
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:293
  14:     0x55fd35745dd9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  15:     0x55fd3574418c - std::rt::lang_start_internal::he5218c8b95d395f2
                               at src/libstd/panicking.rs:272
                               at src/libstd/panic.rs:394
                               at src/libstd/rt.rs:48
  16:     0x55fd35462a28 - std::rt::lang_start::hc166278b92c3cee7
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  17:     0x55fd354633e9 - main
  18:     0x7f900c39db96 - __libc_start_main
  19:     0x55fd35462559 - _start
  20:                0x0 - <unknown>

Process finished with exit code 101
```

My code:

```rust
use nix::sys::signal::Signal::{SIGCHLD, SIGHUP, SIGKILL, SIGTERM};

use signal::trap::Trap;

use std::ops::Add;
use std::time::{Duration, Instant};

fn main() {
    # setup logging boilerplate ...
    let trap = Trap::trap(&[SIGCHLD, SIGHUP, SIGKILL, SIGTERM]);

    loop {
        match trap.wait(Instant::now().add(Duration::from_millis(10))) {
            Some(SIGCHLD) => log::info!("Received SIGCHLD."),
            Some(SIGHUP) => log::info!("Received SIGHUP."),
            Some(SIGKILL) => log::info!("Received SIGKILL."),
            Some(SIGTERM) => log::info!("Received SIGTERM."),
            Some(signal) => log::info!("Received unexpected signal {:?}", signal),
            None => log::info!("Timeout reached."),
        };
    }
}
```

Am I doing something wrong?

**Comment by tailhook** [comment]
Yes, according to the docs:
```
EINVAL The sig argument is not a valid signal number or an attempt is made to catch a signal that cannot be caught or ignore a signal  that  cannot be ignored.
```
Specifically, the `SIGKILL` signal cannot be caught or ignored. If you remove `SIGKILL` signal from the list it should work well.

**Comment by naftulikay** [comment]
My bad, I meant term and quit lol
